# Preprocessing

In [34]:
import polars as pl

In [35]:
df = pl.read_csv("../data/transactions.csv", infer_schema_length=None)

In [36]:
df.head()

shape: (5, 27)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ TRANSACTI ┆ TRANSACTI ┆ TRANSACTI ┆ ORIGINATO ┆ … ┆ SCREENING ┆ PRIORITY_ ┆ CREATED_A ┆ UPDATED_ │
│ ON_ID     ┆ ON_UUID   ┆ ON_REF    ┆ R_COMPANY ┆   ┆ _REQUIRED ┆ FLAG      ┆ T         ┆ AT       │
│ ---       ┆ ---       ┆ ---       ┆ _ID       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---      │
│ i64       ┆ str       ┆ str       ┆ ---       ┆   ┆ bool      ┆ str       ┆ str       ┆ str      │
│           ┆           ┆           ┆ i64       ┆   ┆           ┆           ┆           ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 197       ┆ f6388e95- ┆ TXN-00019 ┆ 2597      ┆ … ┆ true      ┆ NORMAL    ┆ 2026-06-2 ┆ 2026-06- │
│           ┆ 0047-4c6b ┆ 7         ┆           ┆   ┆           ┆           ┆ 4         ┆ 24       │
│           ┆ -b1be-091 ┆           ┆           ┆   ┆           ┆           ┆ 16:17:29  ┆ 16:17:29 │
│           ┆ e4b…      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 213       ┆ 7dce39a5- ┆ TXN-00021 ┆ 3649      ┆ … ┆ true      ┆ NORMAL    ┆ 2026-06-2 ┆ 2026-06- │
│           ┆ 9471-4d81 ┆ 3         ┆           ┆   ┆           ┆           ┆ 4         ┆ 24       │
│           ┆ -8980-101 ┆           ┆           ┆   ┆           ┆           ┆ 16:17:29  ┆ 16:17:29 │
│           ┆ 3a8…      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 399       ┆ 66c378d8- ┆ TXN-00039 ┆ 1750      ┆ … ┆ true      ┆ NORMAL    ┆ 2026-06-2 ┆ 2026-06- │
│           ┆ 6af8-49af ┆ 9         ┆           ┆   ┆           ┆           ┆ 4         ┆ 24       │
│           ┆ -a5c8-c0f ┆           ┆           ┆   ┆           ┆           ┆ 16:17:29  ┆ 16:17:29 │
│           ┆ 450…      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 617       ┆ c5c8b5fc- ┆ TXN-00061 ┆ 3070      ┆ … ┆ true      ┆ NORMAL    ┆ 2026-06-2 ┆ 2026-06- │
│           ┆ 9cd4-486e ┆ 7         ┆           ┆   ┆           ┆           ┆ 4         ┆ 24       │
│           ┆ -a7ef-f8b ┆           ┆           ┆   ┆           ┆           ┆ 16:17:29  ┆ 16:17:29 │
│           ┆ 30d…      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 877       ┆ fb8dd7cd- ┆ TXN-00087 ┆ 29        ┆ … ┆ true      ┆ NORMAL    ┆ 2026-06-2 ┆ 2026-06- │
│           ┆ a3c2-45ca ┆ 7         ┆           ┆   ┆           ┆           ┆ 4         ┆ 24       │
│           ┆ -b211-80b ┆           ┆           ┆   ┆           ┆           ┆ 16:17:29  ┆ 16:17:29 │
│           ┆ d2e…      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [37]:
df.group_by("PRIORITY_FLAG").count()

/var/folders/bd/011x4rxx3zz15h6zg8z96x6w0000gn/T/ipykernel_37992/3533856105.py:1: DeprecationWarning: `GroupBy.count` was renamed; use `GroupBy.len` instead
  df.group_by("PRIORITY_FLAG").count()

shape: (3, 2)
┌───────────────┬────────┐
│ PRIORITY_FLAG ┆ count  │
│ ---           ┆ ---    │
│ str           ┆ u32    │
╞═══════════════╪════════╡
│ MEDIUM        ┆ 17746  │
│ NORMAL        ┆ 130852 │
│ HIGH          ┆ 1402   │
└───────────────┴────────┘

In [38]:
df.group_by("SCREENING_REQUIRED").count()

/var/folders/bd/011x4rxx3zz15h6zg8z96x6w0000gn/T/ipykernel_37992/2737908412.py:1: DeprecationWarning: `GroupBy.count` was renamed; use `GroupBy.len` instead
  df.group_by("SCREENING_REQUIRED").count()

shape: (2, 2)
┌────────────────────┬───────┐
│ SCREENING_REQUIRED ┆ count │
│ ---                ┆ ---   │
│ bool               ┆ u32   │
╞════════════════════╪═══════╡
│ false              ┆ 62276 │
│ true               ┆ 87724 │
└────────────────────┴───────┘

In [39]:
df.filter(
    (pl.col("SCREENING_REQUIRED") == True) & (pl.col("PRIORITY_FLAG") == "NORMAL")
).count()

shape: (1, 27)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ TRANSACTI ┆ TRANSACTI ┆ TRANSACTI ┆ ORIGINATO ┆ … ┆ SCREENING ┆ PRIORITY_ ┆ CREATED_A ┆ UPDATED_ │
│ ON_ID     ┆ ON_UUID   ┆ ON_REF    ┆ R_COMPANY ┆   ┆ _REQUIRED ┆ FLAG      ┆ T         ┆ AT       │
│ ---       ┆ ---       ┆ ---       ┆ _ID       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---      │
│ u32       ┆ u32       ┆ u32       ┆ ---       ┆   ┆ u32       ┆ u32       ┆ u32       ┆ u32      │
│           ┆           ┆           ┆ u32       ┆   ┆           ┆           ┆           ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 68576     ┆ 68576     ┆ 68576     ┆ 68576     ┆ … ┆ 68576     ┆ 68576     ┆ 68576     ┆ 68576    │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [40]:
df.columns

['TRANSACTION_ID',
 'TRANSACTION_UUID',
 'TRANSACTION_REF',
 'ORIGINATOR_COMPANY_ID',
 'BENEFICIARY_COMPANY_ID',
 'BENEFICIARY_NAME',
 'BENEFICIARY_ACCOUNT',
 'BENEFICIARY_BANK_BIC',
 'BENEFICIARY_COUNTRY_ID',
 'TRANSACTION_TYPE',
 'TRANSACTION_SUBTYPE',
 'PAYMENT_PURPOSE',
 'AMOUNT_ORIGINAL',
 'CURRENCY_ORIGINAL',
 'AMOUNT_USD',
 'EXCHANGE_RATE',
 'INITIATED_AT',
 'VALUE_DATE',
 'SETTLED_AT',
 'ORIGINATING_COUNTRY_ID',
 'DESTINATION_COUNTRY_ID',
 'IS_CROSS_BORDER',
 'STATUS',
 'SCREENING_REQUIRED',
 'PRIORITY_FLAG',
 'CREATED_AT',
 'UPDATED_AT']

In [41]:
df.head()

shape: (5, 27)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ TRANSACTI ┆ TRANSACTI ┆ TRANSACTI ┆ ORIGINATO ┆ … ┆ SCREENING ┆ PRIORITY_ ┆ CREATED_A ┆ UPDATED_ │
│ ON_ID     ┆ ON_UUID   ┆ ON_REF    ┆ R_COMPANY ┆   ┆ _REQUIRED ┆ FLAG      ┆ T         ┆ AT       │
│ ---       ┆ ---       ┆ ---       ┆ _ID       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---      │
│ i64       ┆ str       ┆ str       ┆ ---       ┆   ┆ bool      ┆ str       ┆ str       ┆ str      │
│           ┆           ┆           ┆ i64       ┆   ┆           ┆           ┆           ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 197       ┆ f6388e95- ┆ TXN-00019 ┆ 2597      ┆ … ┆ true      ┆ NORMAL    ┆ 2026-06-2 ┆ 2026-06- │
│           ┆ 0047-4c6b ┆ 7         ┆           ┆   ┆           ┆           ┆ 4         ┆ 24       │
│           ┆ -b1be-091 ┆           ┆           ┆   ┆           ┆           ┆ 16:17:29  ┆ 16:17:29 │
│           ┆ e4b…      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 213       ┆ 7dce39a5- ┆ TXN-00021 ┆ 3649      ┆ … ┆ true      ┆ NORMAL    ┆ 2026-06-2 ┆ 2026-06- │
│           ┆ 9471-4d81 ┆ 3         ┆           ┆   ┆           ┆           ┆ 4         ┆ 24       │
│           ┆ -8980-101 ┆           ┆           ┆   ┆           ┆           ┆ 16:17:29  ┆ 16:17:29 │
│           ┆ 3a8…      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 399       ┆ 66c378d8- ┆ TXN-00039 ┆ 1750      ┆ … ┆ true      ┆ NORMAL    ┆ 2026-06-2 ┆ 2026-06- │
│           ┆ 6af8-49af ┆ 9         ┆           ┆   ┆           ┆           ┆ 4         ┆ 24       │
│           ┆ -a5c8-c0f ┆           ┆           ┆   ┆           ┆           ┆ 16:17:29  ┆ 16:17:29 │
│           ┆ 450…      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 617       ┆ c5c8b5fc- ┆ TXN-00061 ┆ 3070      ┆ … ┆ true      ┆ NORMAL    ┆ 2026-06-2 ┆ 2026-06- │
│           ┆ 9cd4-486e ┆ 7         ┆           ┆   ┆           ┆           ┆ 4         ┆ 24       │
│           ┆ -a7ef-f8b ┆           ┆           ┆   ┆           ┆           ┆ 16:17:29  ┆ 16:17:29 │
│           ┆ 30d…      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 877       ┆ fb8dd7cd- ┆ TXN-00087 ┆ 29        ┆ … ┆ true      ┆ NORMAL    ┆ 2026-06-2 ┆ 2026-06- │
│           ┆ a3c2-45ca ┆ 7         ┆           ┆   ┆           ┆           ┆ 4         ┆ 24       │
│           ┆ -b211-80b ┆           ┆           ┆   ┆           ┆           ┆ 16:17:29  ┆ 16:17:29 │
│           ┆ d2e…      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [42]:
dt_df = df.with_columns([
    pl.col(c).str.to_datetime(strict=False) for c in ["INITIATED_AT", "SETTLED_AT", "CREATED_AT", "UPDATED_AT"]
] + [
    pl.col("VALUE_DATE").str.to_date(strict=False)
])

In [43]:
dt_df.head()

shape: (5, 27)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ TRANSACTI ┆ TRANSACTI ┆ TRANSACTI ┆ ORIGINATO ┆ … ┆ SCREENING ┆ PRIORITY_ ┆ CREATED_A ┆ UPDATED_ │
│ ON_ID     ┆ ON_UUID   ┆ ON_REF    ┆ R_COMPANY ┆   ┆ _REQUIRED ┆ FLAG      ┆ T         ┆ AT       │
│ ---       ┆ ---       ┆ ---       ┆ _ID       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---      │
│ i64       ┆ str       ┆ str       ┆ ---       ┆   ┆ bool      ┆ str       ┆ datetime[ ┆ datetime │
│           ┆           ┆           ┆ i64       ┆   ┆           ┆           ┆ μs]       ┆ [μs]     │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 197       ┆ f6388e95- ┆ TXN-00019 ┆ 2597      ┆ … ┆ true      ┆ NORMAL    ┆ 2026-06-2 ┆ 2026-06- │
│           ┆ 0047-4c6b ┆ 7         ┆           ┆   ┆           ┆           ┆ 4         ┆ 24       │
│           ┆ -b1be-091 ┆           ┆           ┆   ┆           ┆           ┆ 16:17:29  ┆ 16:17:29 │
│           ┆ e4b…      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 213       ┆ 7dce39a5- ┆ TXN-00021 ┆ 3649      ┆ … ┆ true      ┆ NORMAL    ┆ 2026-06-2 ┆ 2026-06- │
│           ┆ 9471-4d81 ┆ 3         ┆           ┆   ┆           ┆           ┆ 4         ┆ 24       │
│           ┆ -8980-101 ┆           ┆           ┆   ┆           ┆           ┆ 16:17:29  ┆ 16:17:29 │
│           ┆ 3a8…      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 399       ┆ 66c378d8- ┆ TXN-00039 ┆ 1750      ┆ … ┆ true      ┆ NORMAL    ┆ 2026-06-2 ┆ 2026-06- │
│           ┆ 6af8-49af ┆ 9         ┆           ┆   ┆           ┆           ┆ 4         ┆ 24       │
│           ┆ -a5c8-c0f ┆           ┆           ┆   ┆           ┆           ┆ 16:17:29  ┆ 16:17:29 │
│           ┆ 450…      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 617       ┆ c5c8b5fc- ┆ TXN-00061 ┆ 3070      ┆ … ┆ true      ┆ NORMAL    ┆ 2026-06-2 ┆ 2026-06- │
│           ┆ 9cd4-486e ┆ 7         ┆           ┆   ┆           ┆           ┆ 4         ┆ 24       │
│           ┆ -a7ef-f8b ┆           ┆           ┆   ┆           ┆           ┆ 16:17:29  ┆ 16:17:29 │
│           ┆ 30d…      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 877       ┆ fb8dd7cd- ┆ TXN-00087 ┆ 29        ┆ … ┆ true      ┆ NORMAL    ┆ 2026-06-2 ┆ 2026-06- │
│           ┆ a3c2-45ca ┆ 7         ┆           ┆   ┆           ┆           ┆ 4         ┆ 24       │
│           ┆ -b211-80b ┆           ┆           ┆   ┆           ┆           ┆ 16:17:29  ┆ 16:17:29 │
│           ┆ d2e…      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [45]:
import numpy as np

In [ ]:


dt_df = dt_df.with_columns([
    pl.col("INITIATED_AT").dt.hour().alias("hour"),
    pl.col("INITIATED_AT").dt.weekday().alias("weekday"),  # 1=Mon..7=Sun
])

NameError: name 'np' is not defined

In [46]:
feature_df = dt_df.with_columns([
    (2 * np.pi * pl.col("hour") / 24).sin().alias("hour_sin"),
    (2 * np.pi * pl.col("hour") / 24).cos().alias("hour_cos"),
    (2 * np.pi * pl.col("weekday") / 7).sin().alias("weekday_sin"),
    (2 * np.pi * pl.col("weekday") / 7).cos().alias("weekday_cos"),
])

In [48]:
feature_df.head()

shape: (5, 33)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ TRANSACTI ┆ TRANSACTI ┆ TRANSACTI ┆ ORIGINATO ┆ … ┆ hour_sin  ┆ hour_cos  ┆ weekday_s ┆ weekday_ │
│ ON_ID     ┆ ON_UUID   ┆ ON_REF    ┆ R_COMPANY ┆   ┆ ---       ┆ ---       ┆ in        ┆ cos      │
│ ---       ┆ ---       ┆ ---       ┆ _ID       ┆   ┆ f64       ┆ f64       ┆ ---       ┆ ---      │
│ i64       ┆ str       ┆ str       ┆ ---       ┆   ┆           ┆           ┆ f64       ┆ f64      │
│           ┆           ┆           ┆ i64       ┆   ┆           ┆           ┆           ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 197       ┆ f6388e95- ┆ TXN-00019 ┆ 2597      ┆ … ┆ 1.0       ┆ 6.1232e-1 ┆ -0.433884 ┆ -0.90096 │
│           ┆ 0047-4c6b ┆ 7         ┆           ┆   ┆           ┆ 7         ┆           ┆ 9        │
│           ┆ -b1be-091 ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ e4b…      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 213       ┆ 7dce39a5- ┆ TXN-00021 ┆ 3649      ┆ … ┆ 0.5       ┆ -0.866025 ┆ -2.4493e- ┆ 1.0      │
│           ┆ 9471-4d81 ┆ 3         ┆           ┆   ┆           ┆           ┆ 16        ┆          │
│           ┆ -8980-101 ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ 3a8…      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 399       ┆ 66c378d8- ┆ TXN-00039 ┆ 1750      ┆ … ┆ 0.866025  ┆ -0.5      ┆ 0.433884  ┆ -0.90096 │
│           ┆ 6af8-49af ┆ 9         ┆           ┆   ┆           ┆           ┆           ┆ 9        │
│           ┆ -a5c8-c0f ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ 450…      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 617       ┆ c5c8b5fc- ┆ TXN-00061 ┆ 3070      ┆ … ┆ 0.707107  ┆ -0.707107 ┆ -0.781831 ┆ 0.62349  │
│           ┆ 9cd4-486e ┆ 7         ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ -a7ef-f8b ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ 30d…      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 877       ┆ fb8dd7cd- ┆ TXN-00087 ┆ 29        ┆ … ┆ -0.707107 ┆ 0.707107  ┆ -0.781831 ┆ 0.62349  │
│           ┆ a3c2-45ca ┆ 7         ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ -b211-80b ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ d2e…      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [50]:
import polars as pl
import numpy as np
from sklearn.ensemble import IsolationForest
from sklearn.metrics import classification_report, confusion_matrix, roc_auc_score

# 1. Inspect what you're working with
print(feature_df.head())
print(feature_df.dtypes)

# 2. Separate the label from the features
# PRIORITY_FLAG is presumably categorical (e.g. "HIGH"/"LOW"/"MEDIUM")
# Isolation Forest is unsupervised, so we only use it to evaluate AFTER fitting — never as a training input
label_col = "PRIORITY_FLAG"

# Convert label to binary: HIGH = anomaly-like (1), everything else = normal (0)
# Adjust this mapping if PRIORITY_FLAG has different levels
y_true = feature_df.select(
    (pl.col(label_col) == "HIGH").cast(pl.Int8).alias("y_true")
).to_series().to_numpy()

# 3. Build feature matrix - drop label and any obvious ID/string columns
exclude_cols = [label_col]
non_numeric_cols = [c for c, dt in zip(feature_df.columns, feature_df.dtypes) 
                     if dt not in (pl.Float32, pl.Float64, pl.Int8, pl.Int16, pl.Int32, pl.Int64)]

feature_cols = [c for c in feature_df.columns if c not in exclude_cols and c not in non_numeric_cols]
print(f"\nUsing {len(feature_cols)} numeric features: {feature_cols}")

X = feature_df.select(feature_cols).to_numpy()

# Check for NaNs before fitting - Isolation Forest will error out otherwise
if np.isnan(X).any():
    print("⚠️  NaNs detected in feature matrix — imputing with column median")
    col_medians = np.nanmedian(X, axis=0)
    inds = np.where(np.isnan(X))
    X[inds] = np.take(col_medians, inds[1])

# 4. Fit naive Isolation Forest (no tuning, defaults + a seed)
iso = IsolationForest(n_estimators=100, contamination="auto", random_state=42)
iso.fit(X)

# -1 = anomaly, 1 = normal -> convert to 1 = anomaly, 0 = normal to match y_true convention
raw_pred = iso.predict(X)
y_pred = (raw_pred == -1).astype(int)
scores = iso.decision_function(X)  # lower = more anomalous

# 5. Compare against PRIORITY_FLAG label
print("\n" + "="*60)
print("Isolation Forest vs PRIORITY_FLAG comparison")
print("="*60)

print(f"\nActual HIGH priority count: {y_true.sum():,} / {len(y_true):,} ({y_true.mean()*100:.2f}%)")
print(f"IF flagged anomaly count:   {y_pred.sum():,} / {len(y_pred):,} ({y_pred.mean()*100:.2f}%)")

print("\nConfusion Matrix (rows=actual, cols=predicted):")
print(confusion_matrix(y_true, y_pred))

print("\nClassification Report:")
print(classification_report(y_true, y_pred, target_names=["NOT_HIGH", "HIGH"]))

try:
    auc = roc_auc_score(y_true, -scores)  # negate: lower decision_function = more anomalous = higher risk
    print(f"ROC-AUC (anomaly score vs HIGH priority label): {auc:.4f}")
except ValueError as e:
    print(f"Could not compute AUC: {e}")

# 6. Attach results back to the dataframe for inspection
feature_df = feature_df.with_columns([
    pl.Series("if_anomaly_score", scores),
    pl.Series("if_is_anomaly", y_pred)
])

# Look at rows where IF disagrees with the label — most interesting cases
disagreements = feature_df.filter(
    (pl.col("if_is_anomaly") == 1) & (pl.col(label_col) != "HIGH")
)
print(f"\nIF flagged as anomaly but NOT labeled HIGH: {disagreements.height:,} rows")

missed = feature_df.filter(
    (pl.col("if_is_anomaly") == 0) & (pl.col(label_col) == "HIGH")
)
print(f"Labeled HIGH but IF did NOT flag: {missed.height:,} rows")

shape: (5, 33)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ TRANSACTI ┆ TRANSACTI ┆ TRANSACTI ┆ ORIGINATO ┆ … ┆ hour_sin  ┆ hour_cos  ┆ weekday_s ┆ weekday_ │
│ ON_ID     ┆ ON_UUID   ┆ ON_REF    ┆ R_COMPANY ┆   ┆ ---       ┆ ---       ┆ in        ┆ cos      │
│ ---       ┆ ---       ┆ ---       ┆ _ID       ┆   ┆ f64       ┆ f64       ┆ ---       ┆ ---      │
│ i64       ┆ str       ┆ str       ┆ ---       ┆   ┆           ┆           ┆ f64       ┆ f64      │
│           ┆           ┆           ┆ i64       ┆   ┆           ┆           ┆           ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 197       ┆ f6388e95- ┆ TXN-00019 ┆ 2597      ┆ … ┆ 1.0       ┆ 6.1232e-1 ┆ -0.433884 ┆ -0.90096 │
│           ┆ 0047-4c6b ┆ 7         ┆           ┆   ┆           ┆ 7         ┆           ┆ 9        │
│           ┆ -b1be-091 ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ e4b…      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 213       ┆ 7dce39a5- ┆ TXN-00021 ┆ 3649      ┆ … ┆ 0.5       ┆ -0.866025 ┆ -2.4493e- ┆ 1.0      │
│           ┆ 9471-4d81 ┆ 3         ┆           ┆   ┆           ┆           ┆ 16        ┆          │
│           ┆ -8980-101 ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ 3a8…      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 399       ┆ 66c378d8- ┆ TXN-00039 ┆ 1750      ┆ … ┆ 0.866025  ┆ -0.5      ┆ 0.433884  ┆ -0.90096 │
│           ┆ 6af8-49af ┆ 9         ┆           ┆   ┆           ┆           ┆           ┆ 9        │
│           ┆ -a5c8-c0f ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ 450…      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 617       ┆ c5c8b5fc- ┆ TXN-00061 ┆ 3070      ┆ … ┆ 0.707107  ┆ -0.707107 ┆ -0.781831 ┆ 0.62349  │
│           ┆ 9cd4-486e ┆ 7         ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ -a7ef-f8b ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ 30d…      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 877       ┆ fb8dd7cd- ┆ TXN-00087 ┆ 29        ┆ … ┆ -0.707107 ┆ 0.707107  ┆ -0.781831 ┆ 0.62349  │
│           ┆ a3c2-45ca ┆ 7         ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ -b211-80b ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ d2e…      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘
[Int64, String, String, Int64, Int64, String, String, String, Int64, String, String, String, Float64, String, Float64, Float64, Datetime(time_unit='us', time_zone=None), Date, Datetime(time_unit='us', time_zone=None), Int64, Int64, Boolean, String, Boolean, String, Datetime(time_unit='us', time_zone=None), Datetime(time_unit='us', time_zone=None), Int8, Int8, Float64, Float64, Float64, Float64]

Using 15 numeric features: ['TRANSACTION_ID', 'ORIGINATOR_COMPANY_ID', 'BENEFICIARY_COMPANY_ID', 'BENEFICIARY_COUNTRY_ID', 'AMOUNT_ORIGINAL', 'AMOUNT_USD', 'EXCHANGE_RATE', 'ORIGINATING_COUNTRY_ID', 'DESTINATION_COUNTRY_ID', 'hour', 'weekday', 'hour_sin', 'hour_cos', 'weekday_sin', 'weekday_cos']

============================================================
Isolation Forest vs PRIORITY_FLAG comparison
============================================================

Actual HIGH priority count: 1,402 / 150,000 (0.93%)
IF flagged anomaly count:   71,625 / 150,000 (47.75%)

Confusion Matrix (rows=actual, cols=predicted):
[[78375 70223]
 [    0  1402]]

Classification Report:
              precision    recall  f1-score   support

    NOT_HIGH       1.00      0.53      0.69    148598
        HIGH       0.02      1.00      0.04      1402

    accuracy                           0.53    150000
   macro avg       0.51      0.76      0.36    150000
weighted avg       0.99      0.53      0.68    150000

ROC-AUC (anomaly score vs HIGH priority label): 0.9985

IF flagged as anomaly but NOT labeled HIGH: 70,223 rows
Labeled HIGH but IF did NOT flag: 0 rows

In [51]:
true_rate = y_true.mean()
print(f"True HIGH rate: {true_rate:.4f}")

iso = IsolationForest(n_estimators=100, contamination=true_rate, random_state=42)
iso.fit(X)

raw_pred = iso.predict(X)
y_pred = (raw_pred == -1).astype(int)
scores = iso.decision_function(X)

print(confusion_matrix(y_true, y_pred))
print(classification_report(y_true, y_pred, target_names=["NOT_HIGH", "HIGH"]))

True HIGH rate: 0.0093
[[148298    300]
 [   300   1102]]
              precision    recall  f1-score   support

    NOT_HIGH       1.00      1.00      1.00    148598
        HIGH       0.79      0.79      0.79      1402

    accuracy                           1.00    150000
   macro avg       0.89      0.89      0.89    150000
weighted avg       1.00      1.00      1.00    150000

In [52]:
feature_df = feature_df.with_columns(pl.Series("if_anomaly_score", scores))

k = int(y_true.sum())  # top-1402 most anomalous
top_k = feature_df.sort("if_anomaly_score").head(k)

matched = top_k.filter(pl.col("PRIORITY_FLAG") == "HIGH").height
print(f"Of top {k} most anomalous rows, {matched} are actually labeled HIGH ({matched/k*100:.1f}% precision@k)")

Of top 1402 most anomalous rows, 1102 are actually labeled HIGH (78.6% precision@k)

In [ ]:
df.columns

['TRANSACTION_ID',
 'TRANSACTION_UUID',
 'TRANSACTION_REF',
 'ORIGINATOR_COMPANY_ID',
 'BENEFICIARY_COMPANY_ID',
 'BENEFICIARY_NAME',
 'BENEFICIARY_ACCOUNT',
 'BENEFICIARY_BANK_BIC',
 'BENEFICIARY_COUNTRY_ID',
 'TRANSACTION_TYPE',
 'TRANSACTION_SUBTYPE',
 'PAYMENT_PURPOSE',
 'AMOUNT_ORIGINAL',
 'CURRENCY_ORIGINAL',
 'AMOUNT_USD',
 'EXCHANGE_RATE',
 'INITIATED_AT',
 'VALUE_DATE',
 'SETTLED_AT',
 'ORIGINATING_COUNTRY_ID',
 'DESTINATION_COUNTRY_ID',
 'IS_CROSS_BORDER',
 'STATUS',
 'SCREENING_REQUIRED',
 'PRIORITY_FLAG',
 'CREATED_AT',
 'UPDATED_AT']